name: Backend CI - Run Maven Unit tests

on:
  workflow_dispatch:
  pull_request:
    branches: [ "master", "develop" ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app/Java
        
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
    - name: Build and run Unit/Integration Tests with Maven
      run: mvn -ntp -B verify
